# Portal Configuration

title: "Enterprise AI Portal"
description: "Central portal for departmental AI applications"

# Company branding
company:
  name: "TechCorp Solutions"
  logo_url: "assets/images/logo.svg"
  theme_color: "#4a6fa5"

# User information
user:
  name: "John Smith"
  role: "AI Solutions Manager"
  avatar_url: "assets/images/user-avatar.svg"
  department: "IT Operations"

# AI App Store configuration
app_store:
  title: "AI App Store"
  icon: "fa-solid fa-store"
  description: "Your one-stop marketplace for enterprise AI solutions. Discover, deploy, and manage pre-vetted AI applications tailored for your business needs. Each app is security-tested and optimized for seamless integration with your existing systems."
  banner_image: "assets/images/app-store-banner.svg"

# Departments configuration
departments:
  - name: "Business Operations"
    icon: "fa-solid fa-chart-line"
    description: "Business operations tools that optimize processes, enhance decision-making, and improve operational efficiency."
    apps:
      - name: "Financial Analysis"
        url: "/business/finance"
        icon: "fa-solid fa-chart-bar"
        description: "AI-powered financial analysis tool - Analyze financial data, identify trends, and generate insights to support strategic decision-making."
        business_area: "All"
      - name: "Supply Chain Optimizer"
        url: "/business/supply-chain"
        icon: "fa-solid fa-truck"
        description: "Optimize supply chain operations - Identify bottlenecks, predict disruptions, and recommend optimization strategies for improved efficiency."
        business_area: "Direct"
      - name: "Process Automation"
        url: "/business/automation"
        icon: "fa-solid fa-cogs"
        description: "Business process automation platform - Automate repetitive tasks and workflows to increase productivity and reduce errors."
        business_area: "GMAD"
      - name: "Predictive Analytics"
        url: "/business/analytics"
        icon: "fa-solid fa-chart-pie"
        description: "Advanced predictive analytics - Forecast business trends, customer behaviors, and market changes to support strategic planning."
        business_area: "Marketing"
      - name: "Risk Management"
        url: "/business/risk"
        icon: "fa-solid fa-shield-halved"
        description: "AI-driven risk management system - Identify, assess, and mitigate business risks using predictive modeling and scenario analysis."
        business_area: "Cross-NYLI"
  
  - name: "Software Development"
    icon: "fa-solid fa-code"
    description: "Software development tools that enhance coding productivity, quality, and deployment efficiency."
    apps:
      - name: "Code Generator"
        url: "/software/code-gen"
        icon: "fa-solid fa-file-code"
        description: "AI code generation tool - Generate code snippets and boilerplate code based on natural language descriptions and requirements."
        business_area: "IA"
      - name: "Bug Predictor"
        url: "/software/bug-predict"
        icon: "fa-solid fa-bug"
        description: "Proactive bug detection system - Identify potential bugs and issues before they occur by analyzing code patterns and historical data."
        business_area: "All"
      - name: "API Designer"
        url: "/software/api"
        icon: "fa-solid fa-plug"
        description: "AI-assisted API design tool - Design, document, and test APIs with intelligent suggestions for endpoints, parameters, and security features."
        business_area: "Direct"
      - name: "DevOps Automator"
        url: "/software/devops"
        icon: "fa-solid fa-gears"
        description: "DevOps workflow automation - Streamline CI/CD pipelines, testing, and deployment processes with intelligent optimization."
        business_area: "GMAD"
      - name: "Performance Analyzer"
        url: "/software/performance"
        icon: "fa-solid fa-gauge-high"
        description: "Application performance analyzer - Identify performance bottlenecks, optimize resource usage, and improve application speed and efficiency."
        business_area: "Cross-NYLI"
  
  - name: "IT Operations"
    icon: "fa-solid fa-server"
    description: "IT operations tools that enhance system reliability, security, and infrastructure management."
    apps:
      - name: "Network Monitor"
        url: "/it/network"
        icon: "fa-solid fa-network-wired"
        description: "AI-powered network monitoring - Detect anomalies, predict outages, and optimize network performance using machine learning algorithms."
        business_area: "All"
      - name: "Security Scanner"
        url: "/it/security"
        icon: "fa-solid fa-shield-alt"
        description: "Advanced security vulnerability scanner - Identify security risks and vulnerabilities across systems and applications with AI-driven threat detection."
        business_area: "IA"
      - name: "Cloud Cost Optimizer"
        url: "/it/cloud-cost"
        icon: "fa-solid fa-cloud"
        description: "Cloud resource optimization tool - Analyze cloud usage patterns and recommend cost-saving measures without compromising performance."
        business_area: "Direct"
      - name: "Incident Responder"
        url: "/it/incidents"
        icon: "fa-solid fa-bell"
        description: "Automated incident response system - Detect, categorize, and respond to IT incidents with AI-driven automation and recommendations."
        business_area: "GMAD"
      - name: "System Health Dashboard"
        url: "/it/health"
        icon: "fa-solid fa-heartbeat"
        description: "Comprehensive IT system health monitoring - Get real-time insights into system performance, resource usage, and potential issues."
        business_area: "Marketing"
  
  - name: "Individual Productivity"
    icon: "fa-solid fa-user-clock"
    description: "Tools that enhance personal productivity, communication, and knowledge management for individuals."
    apps:
      - name: "Meeting Summarizer"
        url: "/productivity/meetings"
        icon: "fa-solid fa-video"
        description: "AI meeting notes generator - Automatically capture, summarize, and organize key points and action items from virtual meetings."
        business_area: "Cross-NYLI"
      - name: "Smart Calendar"
        url: "/productivity/calendar"
        icon: "fa-solid fa-calendar"
        description: "AI-powered calendar assistant - Optimize scheduling, suggest ideal meeting times, and provide intelligent reminders and preparation tips."
        business_area: "All"
      - name: "Email Assistant"
        url: "/productivity/email"
        icon: "fa-solid fa-envelope"
        description: "Email productivity tool - Sort, prioritize, and suggest responses to emails with AI-driven intelligence and automation."
        business_area: "IA"
      - name: "Document Generator"
        url: "/productivity/documents"
        icon: "fa-solid fa-file-alt"
        description: "Smart document creation tool - Generate professional documents, reports, and presentations using templates and AI content suggestions."
        business_area: "Direct"
      - name: "Knowledge Assistant"
        url: "/productivity/knowledge"
        icon: "fa-solid fa-brain"
        description: "Personal knowledge management assistant - Organize notes, research, and information with AI-powered categorization and retrieval."
        business_area: "GMAD"
  
  - name: "HR"
    icon: "fa-solid fa-user-group"
    description: "Human resources tools leveraging AI to improve recruitment, retention, and performance management processes."
    apps:
      - name: "Candidate Matcher"
        url: "/hr/candidates"
        icon: "fa-solid fa-user-check"
        description: "AI-powered candidate matching system - Match job requirements with candidate skills and experience to identify the best fits for open positions."
        business_area: "Marketing"
      - name: "Employee Sentiment Analyzer"
        url: "/hr/sentiment"
        icon: "fa-solid fa-face-smile"
        description: "Employee satisfaction monitoring tool - Analyze feedback, surveys, and communication patterns to gauge employee sentiment and engagement."
        business_area: "Cross-NYLI"
      - name: "Training Recommender"
        url: "/hr/training"
        icon: "fa-solid fa-graduation-cap"
        description: "Personalized learning recommendation system - Suggest relevant training and development opportunities based on skills, goals, and career paths."
        business_area: "All"
      - name: "Performance Predictor"
        url: "/hr/performance"
        icon: "fa-solid fa-chart-line"
        description: "AI performance evaluation system - Analyze employee performance data to identify patterns and predict future performance with objective metrics."
        business_area: "IA"
      - name: "Retention Analyzer"
        url: "/hr/retention"
        icon: "fa-solid fa-user-shield"
        description: "Employee retention prediction tool - Identify employees at risk of leaving and suggest personalized retention strategies."
        business_area: "Direct"

# Shared applications
shared:
  title: "Shared Apps"
  icon: "fa-solid fa-share-nodes"
  description: "Cross-departmental AI tools accessible to all employees for common business needs and productivity enhancement."
  apps:
    - name: "Text Analyzer"
      url: "/shared/text-analyzer"
      icon: "fa-solid fa-font"
      description: "Advanced text analysis tool - Process and extract insights from various text sources with sentiment analysis, entity recognition, and keyword extraction."
      business_area: "All"
    - name: "Image Generator"
      url: "/shared/image-generator"
      icon: "fa-solid fa-image"
      description: "AI-powered image creation - Generate custom images based on text prompts with control over style, content, and composition."
      business_area: "Marketing"
    - name: "Voice Assistant"
      url: "/shared/voice-assistant"
      icon: "fa-solid fa-microphone"
      description: "Voice recognition and response system - Enable voice commands and dictation with multilingual support and custom vocabulary training."
      business_area: "IA"
    - name: "Document AI"
      url: "/shared/docs"
      icon: "fa-solid fa-file-pdf"
      description: "Document processing and analysis - Extract insights from PDFs, Word docs, and images with AI-powered analysis. Supports OCR, entity extraction, and automated summarization."
      business_area: "Cross-NYLI"
    - name: "Data Visualization"
      url: "/shared/viz"
      icon: "fa-solid fa-chart-pie"
      description: "Intelligent data visualization platform - Create interactive dashboards and reports with AI-suggested visualizations based on your data patterns and insights."
      business_area: "GMAD"