# Portal Configuration

title: "Enterprise AI Portal"
description: "Central portal for departmental AI applications"

# Company branding
company:
  name: "TechCorp Solutions"
  logo_url: "assets/images/logo.svg"
  theme_color: "#4a6fa5"

# User information
user:
  name: "John Smith"
  role: "AI Solutions Manager"
  avatar_url: "assets/images/user-avatar.svg"
  department: "IT"

# AI App Store configuration
app_store:
  title: "AI App Store"
  icon: "fa-solid fa-store"
  description: "Your one-stop marketplace for enterprise AI solutions. Discover, deploy, and manage pre-vetted AI applications tailored for your business needs. Each app is security-tested and optimized for seamless integration with your existing systems."
  banner_image: "assets/images/app-store-banner.svg"

# Departments configuration
departments:
  - name: "Finance"
    icon: "fa-solid fa-chart-line"
    description: "Financial AI tools that optimize budgeting, forecasting, and expense tracking to maximize fiscal efficiency and minimize risk."
    apps:
      - name: "Financial Forecasting"
        url: "/finance/forecast"
        icon: "fa-solid fa-chart-bar"
        description: "AI-powered financial forecasting tool - Predict financial outcomes using historical data and machine learning models that account for market trends and internal factors."
      - name: "Expense Analysis"
        url: "/finance/expenses"
        icon: "fa-solid fa-receipt"
        description: "Auto-categorization of expenses using AI - Automatically categorize and analyze expense reports with ML, identifying patterns and potential cost-saving opportunities."
      - name: "Fraud Detection"
        url: "/finance/fraud"
        icon: "fa-solid fa-shield-halved"
        description: "AI-driven fraud detection system - Identify suspicious transactions and activities using machine learning algorithms that detect anomalous patterns and behaviors in financial data."
  
  - name: "Marketing"
    icon: "fa-solid fa-bullhorn"
    description: "Marketing tools powered by AI to enhance customer targeting, campaign performance, and brand sentiment analysis."
    apps:
      - name: "Customer Segmentation"
        url: "/marketing/segments"
        icon: "fa-solid fa-users-viewfinder"
        description: "AI segmentation of customer base - Group customers based on behavior patterns, demographics, and purchasing history to enable targeted marketing strategies."
      - name: "Campaign Optimizer"
        url: "/marketing/campaigns"
        icon: "fa-solid fa-bullseye"
        description: "Optimize marketing campaigns with ML - Use AI to determine the best channels, timing, and content for marketing campaigns to maximize ROI."
      - name: "Sentiment Analyzer"
        url: "/marketing/sentiment"
        icon: "fa-solid fa-face-smile"
        description: "Social media sentiment analysis - Monitor and analyze customer sentiment across social platforms to gauge brand perception and identify emerging trends or issues."
  
  - name: "Operations"
    icon: "fa-solid fa-cogs"
    description: "Operations-focused AI applications that streamline supply chains, enhance quality control, and optimize resource allocation."
    apps:
      - name: "Supply Chain Prediction"
        url: "/operations/supply"
        icon: "fa-solid fa-truck"
        description: "Predict supply chain disruptions - Identify potential disruptions before they occur using AI models trained on historical data and external factors."
      - name: "Quality Control"
        url: "/operations/quality"
        icon: "fa-solid fa-check-circle"
        description: "AI-based quality control system - Automated visual inspection and anomaly detection system that identifies defects in real-time."
      - name: "Resource Optimizer"
        url: "/operations/resources"
        icon: "fa-solid fa-diagram-project"
        description: "AI resource allocation system - Optimize staffing, equipment, and material allocation using ML algorithms that balance workloads and minimize idle time."
  
  - name: "HR"
    icon: "fa-solid fa-user-group"
    description: "Human resources tools leveraging AI to improve recruitment, retention, and performance management processes."
    apps:
      - name: "Resume Screening"
        url: "/hr/resumes"
        icon: "fa-solid fa-file-lines"
        description: "AI-powered resume screening tool - Quickly identify qualified candidates by matching resumes to job requirements using NLP and semantic understanding."
      - name: "Employee Attrition Model"
        url: "/hr/attrition"
        icon: "fa-solid fa-user-minus"
        description: "Predict employee attrition risks - ML model that identifies employees at risk of leaving based on various factors to enable proactive retention strategies."
      - name: "Performance Analytics"
        url: "/hr/performance"
        icon: "fa-solid fa-gauge-high"
        description: "AI performance evaluation system - Analyze employee performance data to identify patterns, provide objective assessments, and recommend personalized development opportunities."
  
  - name: "IT"
    icon: "fa-solid fa-laptop-code"
    description: "IT management solutions using AI to predict incidents, improve code quality, and enhance network security."
    apps:
      - name: "Incident Prediction"
        url: "/it/incidents"
        icon: "fa-solid fa-triangle-exclamation"
        description: "Predict IT incidents before they occur - Identify patterns in system behavior that precede incidents to enable preventative maintenance and reduce downtime."
      - name: "Automated Code Review"
        url: "/it/code"
        icon: "fa-solid fa-code"
        description: "AI-assisted code review system - AI system that analyzes code for bugs, security vulnerabilities, and adherence to best practices."
      - name: "Network Anomaly Detection"
        url: "/it/network"
        icon: "fa-solid fa-network-wired"
        description: "AI network security monitoring - Detect unusual network activity and potential security threats using ML algorithms that establish baseline behavior and identify deviations."

# Shared applications
shared:
  title: "Shared Apps"
  icon: "fa-solid fa-share-nodes"
  description: "Cross-departmental AI tools accessible to all employees for common business needs and productivity enhancement."
  apps:
    - name: "Text Analyzer"
      url: "/store/text-analyzer"
      icon: "fa-solid fa-font"
      description: "Advanced text analysis tool - Process and extract insights from various text sources with sentiment analysis, entity recognition, and keyword extraction."
    - name: "Image Generator"
      url: "/store/image-generator"
      icon: "fa-solid fa-image"
      description: "AI-powered image creation - Generate custom images based on text prompts with control over style, content, and composition."
    - name: "Voice Assistant"
      url: "/store/voice-assistant"
      icon: "fa-solid fa-microphone"
      description: "Voice recognition and response system - Enable voice commands and dictation with multilingual support and custom vocabulary training."
    - name: "Document AI"
      url: "/shared/docs"
      icon: "fa-solid fa-file-pdf"
      description: "Document processing and analysis - Extract insights from PDFs, Word docs, and images with AI-powered analysis. Supports OCR, entity extraction, and automated summarization."
    - name: "Chatbot Assistant"
      url: "/shared/chat"
      icon: "fa-solid fa-comment-dots"
      description: "General-purpose AI chatbot - An intelligent conversational assistant that helps with common queries, provides system information, and routes complex issues to appropriate teams."
    - name: "Data Visualization"
      url: "/shared/viz"
      icon: "fa-solid fa-chart-pie"
      description: "Intelligent data visualization platform - Create interactive dashboards and reports with AI-suggested visualizations based on your data patterns and insights."