# Portal Configuration

title: "Enterprise AI Portal"
description: "Central portal for departmental AI applications"

# Company branding
company:
  name: "TechCorp Solutions"
  logo_url: "assets/images/logo.svg"
  theme_color: "#4a6fa5"

# User information
user:
  name: "John Smith"
  role: "AI Solutions Manager"
  avatar_url: "assets/images/user-avatar.svg"
  department: "IT Operations"

# Department header colors
department_colors:
  Business Operations: "#2E7D32"  # Green
  Software Development: "#C62828"  # Red
  IT Operations: "#0277BD"  # Blue
  Individual Productivity: "#6A1B9A"  # Purple
  HR: "#EF6C00"  # Orange
  App Store: "#1565C0"  # Blue
  default: "#4a6fa5"  # Default fallback color

# Business Area Icons
business_area_icons:
  Direct: "fa-solid fa-handshake"
  GBS: "fa-solid fa-globe"
  GMAD: "fa-solid fa-industry"
  IA: "fa-solid fa-piggy-bank"
  NYLIM: "fa-solid fa-chart-line"

# AI App Store configuration
app_store:
  title: "AI App Store"
  icon: "fa-solid fa-store"
  description: "Your one-stop marketplace for enterprise AI solutions designed specifically for investment company strategic businesses. Discover, deploy, and manage pre-vetted AI applications tailored for financial services, asset management, and insurance operations. Each app is security-tested and optimized for seamless integration with your existing investment systems."
  banner_image: "assets/images/app-store-banner.svg"
  apps:
    - name: "Document AI"
      url: "https://ai-apps.example.com/document-ai"
      contact_url: "https://support.example.com/document-ai"
      icon: "fa-solid fa-file-alt"
      description: "Intelligent document processing - Extract information from documents, categorize content, and automate document-based workflows."
      business_area: "Direct"
    - name: "Chatbot Assistant"
      url: "https://ai-apps.example.com/chatbot"
      contact_email: "chatbot-support@example.com"
      icon: "fa-solid fa-comments"
      description: "Enterprise AI chatbot platform - Build, deploy, and manage conversational AI assistants for customer service and employee support."
      business_area: "GBS"
    - name: "Data Visualization"
      url: "https://ai-apps.example.com/data-viz"
      contact_url: "https://help.example.com/data-visualization"
      icon: "fa-solid fa-chart-simple"
      description: "AI-powered data visualization tool - Create interactive, insightful visualizations from complex datasets with minimal effort."
      business_area: "NYLIM" 
    - name: "Text Analyzer"
      url: "https://ai-apps.example.com/text-analysis"
      contact_email: "text-support@example.com"
      icon: "fa-solid fa-align-left"
      description: "Natural language processing toolkit - Analyze text for sentiment, topics, entities, and insights using advanced NLP algorithms."
      business_area: "IA"
    - name: "Image Generator"
      url: "https://ai-apps.example.com/image-generator"
      contact_url: "https://support.example.com/image-gen"
      icon: "fa-solid fa-image"
      description: "AI image creation tool - Generate custom images, graphics, and visual assets based on text descriptions and parameters."
      business_area: "GMAD"
    - name: "Voice Assistant"
      url: "https://ai-apps.example.com/voice"
      contact_email: "voice-support@example.com"
      icon: "fa-solid fa-microphone"
      description: "Enterprise voice AI solution - Implement voice-enabled assistants and interfaces for applications and services."
      business_area: "Direct"

# Departments configuration
departments:
  - name: "Business Operations"
    icon: "fa-solid fa-briefcase"
    description: "Tools for optimizing business processes and financial operations"
    apps:
      - name: "Financial Analysis"
        url: "/finance/analysis"
        contact: "mailto:financial-support@example.com"
        icon: "fa-solid fa-chart-line"
        description: "Analyze financial data and create forecasts using AI models trained on historical business data."
        business_area: "IA"
      - name: "Supply Chain Optimizer"
        url: "/operations/supply-chain"
        contact: "https://support.example.com/supply-chain"
        icon: "fa-solid fa-truck"
        description: "Optimize logistics and inventory management with our AI-powered supply chain prediction tool."
        business_area: "Direct"
      - name: "Process Automation"
        url: "/business/automation"
        icon: "fa-solid fa-cogs"
        description: "Business process automation platform - Automate repetitive tasks and workflows to increase productivity and reduce errors."
        business_area: "GMAD"
      - name: "Predictive Analytics"
        url: "/business/analytics"
        icon: "fa-solid fa-chart-pie"
        description: "Advanced predictive analytics - Forecast business trends, customer behaviors, and market changes to support strategic planning."
        business_area: "GBS"
      - name: "Risk Management"
        url: "/business/risk"
        icon: "fa-solid fa-shield-halved"
        description: "AI-driven risk management system - Identify, assess, and mitigate business risks using predictive modeling and scenario analysis."
        business_area: "NYLIM"
  
  - name: "Software Development"
    icon: "fa-solid fa-code"
    description: "Software development tools that enhance coding productivity, quality, and deployment efficiency."
    apps:
      - name: "Code Generator"
        url: "/software/code-gen"
        icon: "fa-solid fa-file-code"
        description: "AI code generation tool - Generate code snippets and boilerplate code based on natural language descriptions and requirements."
        business_area: "IA"
      - name: "Bug Predictor"
        url: "/software/bug-predict"
        icon: "fa-solid fa-bug"
        description: "Proactive bug detection system - Identify potential bugs and issues before they occur by analyzing code patterns and historical data."
        business_area: "IA"
      - name: "API Designer"
        url: "/software/api"
        icon: "fa-solid fa-plug"
        description: "AI-assisted API design tool - Design, document, and test APIs with intelligent suggestions for endpoints, parameters, and security features."
        business_area: "Direct"
      - name: "DevOps Automator"
        url: "/software/devops"
        icon: "fa-solid fa-gears"
        description: "DevOps workflow automation - Streamline CI/CD pipelines, testing, and deployment processes with intelligent optimization."
        business_area: "GMAD"
      - name: "Performance Analyzer"
        url: "/software/performance"
        icon: "fa-solid fa-gauge-high"
        description: "Application performance analyzer - Identify performance bottlenecks, optimize resource usage, and improve application speed and efficiency."
        business_area: "NYLIM"
  
  - name: "IT Operations"
    icon: "fa-solid fa-server"
    description: "IT operations tools that enhance system reliability, security, and infrastructure management."
    apps:
      - name: "Network Monitor"
        url: "/it/network"
        contact: "network-support@example.com"
        icon: "fa-solid fa-network-wired"
        description: "AI-powered network monitoring - Detect anomalies, predict outages, and optimize network performance using machine learning algorithms."
        business_area: "Direct"
      - name: "Security Scanner"
        url: "/it/security"
        contact: "https://security-support.example.com"
        icon: "fa-solid fa-shield-alt"
        description: "Advanced security vulnerability scanner - Identify security risks and vulnerabilities across systems and applications with AI-driven threat detection."
        business_area: "IA"
      - name: "Cloud Cost Optimizer"
        url: "/it/cloud-cost"
        icon: "fa-solid fa-cloud"
        description: "Cloud resource optimization tool - Analyze cloud usage patterns and recommend cost-saving measures without compromising performance."
        business_area: "Direct"
      - name: "Incident Responder"
        url: "/it/incidents"
        icon: "fa-solid fa-bell"
        description: "Automated incident response system - Detect, categorize, and respond to IT incidents with AI-driven automation and recommendations."
        business_area: "GMAD"
      - name: "System Health Dashboard"
        url: "/it/health"
        icon: "fa-solid fa-heartbeat"
        description: "Comprehensive IT system health monitoring - Get real-time insights into system performance, resource usage, and potential issues."
        business_area: "GBS"
  
  - name: "Individual Productivity"
    icon: "fa-solid fa-user-clock"
    description: "Tools that enhance personal productivity, communication, and knowledge management for individuals."
    apps:
      - name: "Meeting Summarizer"
        url: "/productivity/meetings"
        icon: "fa-solid fa-video"
        description: "AI meeting notes generator - Automatically capture, summarize, and organize key points and action items from virtual meetings."
        business_area: "NYLIM"
      - name: "Smart Calendar"
        url: "/productivity/calendar"
        icon: "fa-solid fa-calendar"
        description: "AI-powered calendar assistant - Optimize scheduling, suggest ideal meeting times, and provide intelligent reminders and preparation tips."
        business_area: "GBS"
      - name: "Email Assistant"
        url: "/productivity/email"
        icon: "fa-solid fa-envelope"
        description: "Email productivity tool - Sort, prioritize, and suggest responses to emails with AI-driven intelligence and automation."
        business_area: "IA"
      - name: "Document Generator"
        url: "/productivity/documents"
        icon: "fa-solid fa-file-alt"
        description: "Smart document creation tool - Generate professional documents, reports, and presentations using templates and AI content suggestions."
        business_area: "Direct"
      - name: "Knowledge Assistant"
        url: "/productivity/knowledge"
        icon: "fa-solid fa-brain"
        description: "Personal knowledge management assistant - Organize notes, research, and information with AI-powered categorization and retrieval."
        business_area: "GMAD"
  
  - name: "HR"
    icon: "fa-solid fa-user-group"
    description: "Human resources tools leveraging AI to improve recruitment, retention, and performance management processes."
    apps:
      - name: "Candidate Matcher"
        url: "/hr/candidates"
        icon: "fa-solid fa-user-check"
        description: "AI-powered candidate matching system - Match job requirements with candidate skills and experience to identify the best fits for open positions."
        business_area: "GBS"
      - name: "Employee Sentiment Analyzer"
        url: "/hr/sentiment"
        icon: "fa-solid fa-face-smile"
        description: "Employee satisfaction monitoring tool - Analyze feedback, surveys, and communication patterns to gauge employee sentiment and engagement."
        business_area: "NYLIM"
      - name: "Training Recommender"
        url: "/hr/training"
        icon: "fa-solid fa-graduation-cap"
        description: "Personalized learning recommendation system - Suggest relevant training and development opportunities based on skills, goals, and career paths."
        business_area: "IA"
      - name: "Performance Predictor"
        url: "/hr/performance"
        icon: "fa-solid fa-chart-line"
        description: "AI performance evaluation system - Analyze employee performance data to identify patterns and predict future performance with objective metrics."
        business_area: "IA"
      - name: "Retention Analyzer"
        url: "/hr/retention"
        icon: "fa-solid fa-user-shield"
        description: "Employee retention prediction tool - Identify employees at risk of leaving and suggest personalized retention strategies."
        business_area: "Direct"